apiVersion: v1
kind: Pod
metadata:
  name: react-app
  labels:
    app: react-app
spec:
  nodeName:  gaganchohan-nodepool-cjk54
  containers:
  - name: react-app-container
    image: reactregistrygagan.azurecr.io/reactregistrygagan.azurecr.io:v2
    # image: salamflamo/react-hello
    resources:
      requests:
        memory: "500Mi"
        cpu: 500m
      limits:
        memory: "600Mi"
        cpu: 600m
  imagePullSecrets:
    - name: image-pull-secret-react-ingress

# Create secret like this

# kubectl create secret docker-registry image-pull-secret \
#   --docker-server=reactregistrygagan.azurecr.io \
#   --docker-username=<username> \
#   --docker-password=<password> \
#   --docker-email=<email> -o yaml --dry-run

# copy and paste it in a file and then apply
    