apiVersion: v1
kind: Pod
metadata:
  name: react-app
  labels:
    app: react-app
spec:
  nodeName:  gaganchohan-nodepool-cjk54
  containers:
  - name: react-app-container
    image: salamflamo/react-hello
    resources:
      requests:
        memory: "500Mi"
        cpu: 500m
      limits:
        memory: "600Mi"
        cpu: 600m
    # ports:
    #   - containerPort: 8080