apiVersion: v1
data:
  .dockerconfigjson: <my_secret>
kind: Secret
metadata:
  creationTimestamp: null
  name: image-pull-secret-react-ingress  
type: kubernetes.io/dockerconfigjson

# Create secret like this

# kubectl create secret docker-registry image-pull-secret \
#   --docker-server=reactregistrygagan.azurecr.io \
#   --docker-username=<username> \
#   --docker-password=<password> \
#   --docker-email=<email> -o yaml --dry-run

# copy and paste it in a file and then apply