apiVersion: v1
kind: Pod
metadata:
  name: pod-example
spec:
  nodeName:  gaganchohan-nodepool-cjk54
  containers:
  - name: test-name1
    image: redis
    resources:
      requests:
        memory: "100Mi"
        cpu: 200m
      limits:
        memory: "200Mi"
        cpu: 200m
       